name: docker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            docker build -t ${INPUT_REGISTRY}/$(gha name -u anzerr -t app) -t ${INPUT_REGISTRY}/$(gha name -u anzerr -t app -v latest) . &&
            docker push ${INPUT_REGISTRY}/$(gha name -u anzerr -t app) &&
            docker push ${INPUT_REGISTRY}/$(gha name -u anzerr -t app -v latest)
